stages:
  prepare:
    cmd: python src/prepare.py ../../data/forestfires.csv data/prepared
    deps:
    - ../../data/forestfires.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.mean
    - featurize.std
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features scores.json pred_actual.json
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - scores.json:
        cache: false
    plots:
    - pred_actual.json:
        cache: false
