# Random
random_seed: 100

# Data
target: null
training_frac: 0.8
fold_strategy: kfold
k_fold: 5
fold_groups: null
ignore_features: null
polynomial_features: false
polynomial_degree: 2
feature_selection: false
feature_selection_threshold: 0.8
feature_selection_method: classic
feature_interaction: false
feature_ratio: false
interaction_threshold: 0.01
remove_multicollinearity: false
categorical_features: null
ordinal_features: null
numeric_features: null

# Training
search_algorithm: random
custom_grid: null
distributed_search_algorithm: optuna
search_library: scikit-learn 
distributed_search_library: tune-sklearn
imputation_type: simple
iterative_imputation_iters: 5
meta_model: dt
n_select: 5
n_estimators: 10
n_iter: 10
turbo: false
supervised_estimator: lr

# Evaluation
evaluation_metric: MSE
  

