version: "3.5"

services:
  grafana:
    image: "grafana/grafana:${GRAFANA_TAG}"
    container_name: "${ML_PIPELINE_PROJECT_NAME}_grafana"
    user: "472"
    hostname: grafana
    restart: always
    stop_grace_period: 60s
    user: "0"
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      GF_INSTALL_PLUGINS: $GF_INSTALL_PLUGINS
    depends_on:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana

  portainer:
    image: "portainer/portainer:${PORTAINER_TAG}"
    container_name: "${ML_PIPELINE_PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    stop_grace_period: 60s
    restart: always
    ports:
      - ${PORTAINER_PORT}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
      name: ml_pipeline