stages:
  generate:
    cmd: python day_generator.py
    deps:
    - ../../../data/day.csv
    - day_generator.py
    params:
    - day.mean
    - day.seed
    - day.split
    - day.std
    outs:
    - out/days.csv
