files:
  day: ../../../data/day.csv
  forest_fires: ../../../data/forestfires.csv
  out_dir: ../../../out
  generations: 5
  population_size: 5
  cv: 5
  random_state: 100
  n_jobs: -1
  max_time_mins: 1
  max_eval_time_mins: 1
